modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="factori20"
version="${file.jarVersion}"
displayName="Factori0 2.0"
description='''
A Mod Description
'''
[[dependencies.factori20]]
    modId="forge"
    mandatory=true
    versionRange="[43.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.factori20]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

